import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import PDFDocument from 'pdfkit';

export const runtime = 'nodejs';

function getSmtpConfig() {
  const host = process.env.SMTP_HOST || process.env.REPORT_SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || process.env.REPORT_SMTP_PORT || 587);
  const user = process.env.SMTP_USER || process.env.REPORT_SMTP_USER;
  const pass = process.env.SMTP_PASS || process.env.REPORT_SMTP_PASS;
  const from = process.env.SMTP_FROM || process.env.REPORT_EMAIL_FROM || user;
  const to = process.env.REPORT_EMAIL_TO || process.env.SUPERVISOR_EMAIL;
  const secure = String(process.env.SMTP_SECURE || process.env.REPORT_SMTP_SECURE || '').toLowerCase() === 'true' || port === 465;

  if (!host || !user || !pass || !from || !to) {
    return { ok: false, missing: { host: !host, user: !user, pass: !pass, from: !from, to: !to } };
  }

  return { ok: true, host, port, secure, auth: { user, pass }, from, to };
}

function safeText(value, fallback = '—') {
  const text = String(value ?? '').trim();
  return text || fallback;
}

function addKeyValue(doc, label, value) {
  doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
  doc.font('Helvetica').text(safeText(value));
}

function buildPdf(report = {}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 42, bufferPages: true });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    const title = `${safeText(report.facility, 'Facility')} daily checklist report`;
    doc.font('Helvetica-Bold').fontSize(20).text(title);
    doc.moveDown(0.25);
    doc.font('Helvetica').fontSize(11).fillColor('#475569').text(`${safeText(report.dayLabel)} · ${safeText(report.staffName, 'Cleaner')}`);
    doc.moveDown();

    doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(13).text('Summary');
    doc.moveDown(0.35);
    doc.fontSize(10).font('Helvetica');
    const totals = report.totals || {};
    addKeyValue(doc, 'Completed', `${totals.completed ?? 0}/${totals.total ?? 0}`);
    addKeyValue(doc, 'Partial', totals.partial ?? 0);
    addKeyValue(doc, 'Resolved issues', totals.resolvedIssues ?? 0);
    addKeyValue(doc, 'Unresolved issues', totals.unresolvedIssues ?? 0);
    addKeyValue(doc, 'Photos', totals.photoCount ?? 0);
    addKeyValue(doc, 'Notes', totals.noteCount ?? 0);
    doc.moveDown();

    const tasks = Array.isArray(report.tasks) ? report.tasks : [];
    doc.font('Helvetica-Bold').fontSize(13).text('Checklist');
    doc.moveDown(0.4);

    if (!tasks.length) {
      doc.font('Helvetica').fontSize(10).text('No checklist rows were supplied for this report.');
    }

    tasks.forEach((task, index) => {
      if (doc.y > 735) doc.addPage();
      doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(10).text(`${String(index + 1).padStart(2, '0')}. ${safeText(task.title, 'Task')}`);
      doc.font('Helvetica').fontSize(9).fillColor('#334155');
      doc.text(`${safeText(task.zone)} · ${safeText(task.group)} · Grade: ${safeText(task.grade, 'Not graded')} · Photos: ${task.photoCount ?? 0}`);
      if (task.addedToday) doc.fillColor('#0369a1').text('Added task');
      if (task.resolvedIssue) doc.fillColor('#047857').text('Resolved issue');
      if (task.issueNote) doc.fillColor('#7c2d12').text(`Note: ${task.issueNote}`);
      if (task.resolutionNote) doc.fillColor('#047857').text(`Resolution: ${task.resolutionNote}`);
      doc.moveDown(0.45);
    });

    const pageRange = doc.bufferedPageRange();
    for (let i = pageRange.start; i < pageRange.start + pageRange.count; i += 1) {
      doc.switchToPage(i);
      doc.fillColor('#94a3b8').fontSize(8).text(`Generated by Cienna Cleaning · Page ${i + 1} of ${pageRange.count}`, 42, 800, { align: 'center' });
    }

    doc.end();
  });
}

function filenameFor(report = {}) {
  const facility = safeText(report.facility, 'facility').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const day = safeText(report.day, 'report').replace(/[^0-9-]+/g, '');
  return `${facility || 'facility'}-daily-report-${day || 'report'}.pdf`;
}

export async function POST(request) {
  const smtp = getSmtpConfig();
  if (!smtp.ok) {
    return NextResponse.json({ error: 'PDF email is not configured yet. Set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM, and REPORT_EMAIL_TO in Railway.', missing: smtp.missing }, { status: 503 });
  }

  const payload = await request.json().catch(() => null);
  if (!payload?.report) {
    return NextResponse.json({ error: 'Missing report payload.' }, { status: 400 });
  }

  const pdf = await buildPdf(payload.report);
  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: smtp.secure,
    auth: smtp.auth,
  });

  const subject = `${safeText(payload.report.facility, 'Facility')} daily checklist report - ${safeText(payload.report.dayLabel, payload.report.day)}`;
  await transporter.sendMail({
    from: smtp.from,
    to: smtp.to,
    subject,
    text: [
      `${safeText(payload.report.facility, 'Facility')} daily checklist report`,
      `Date: ${safeText(payload.report.dayLabel, payload.report.day)}`,
      `Cleaner: ${safeText(payload.report.staffName, 'Cleaner')}`,
      '',
      'The PDF report is attached.',
    ].join('\n'),
    attachments: [{ filename: filenameFor(payload.report), content: pdf, contentType: 'application/pdf' }],
  });

  return NextResponse.json({ ok: true });
}
